export type IconType =
  | 'account_circle'
  | 'add'
  | 'apartment'
  | 'arrow_back'
  | 'arrow_drop_down'
  | 'close'
  | 'delete'
  | 'edit'
  | 'home'
  | 'image'
  | 'iron'
  | 'link'
  | 'logout'
  | 'person'
  | 'raven'
  | 'visibility'
  | 'visibility_off';
